import 'package:flutter/material.dart';
import 'package:gen_surat/core/themes/app_colors.dart';
import 'package:gen_surat/presentation/pages/document_menu/models/document_item.dart';
import 'package:gen_surat/presentation/routes/route_names.dart';

class DocumentConstants {
  static List<DocumentItem> get getDocumentsIpnu => [
    DocumentItem(
      title: 'Surat Permohonan Pengesahan',
      description: 'Pengajuan surat pengesahan untuk kepengurusan IPNU',
      icon: Icons.description,
      route: RouteNames.suratPermohonanPengesahanIpnu,
      isAvailable: true,
      gradient: [AppColors.ipnuPrimaryLight, AppColors.ipnuPrimaryDark],
    ),
    DocumentItem(
      title: 'Surat Keputusan',
      description: 'Pembuatan surat keputusan untuk kepengurusan IPNU',
      icon: Icons.gavel,
      route: RouteNames.suratKeputusanIpnu,
      isAvailable: true,
      gradient: [AppColors.ipnuPrimaryLight, AppColors.ipnuPrimaryDark],
    ),
    DocumentItem(
      title: 'Berita Acara Pemilihan Ketua',
      description: 'Berita acara untuk dokumentasi pemilihan ketua IPNU',
      icon: Icons.event,
      route: RouteNames.beritaAcaraPemilihanKetuaIpnu,
      isAvailable: true,
      gradient: [AppColors.ipnuPrimaryLight, AppColors.ipnuPrimaryDark],
    ),
    DocumentItem(
      title: 'Susunan Pengurus',
      description: 'Susunan kepengurusan organisasi IPNU',
      icon: Icons.groups,
      route: RouteNames.susunanPengurusIpnu,
      isAvailable: true,
      gradient: [AppColors.ipnuPrimaryLight, AppColors.ipnuPrimaryDark],
    ),
    DocumentItem(
      title: 'Curriculum Vitae',
      description: 'Template CV untuk anggota IPNU',
      icon: Icons.person,
      route: RouteNames.curriculumVitaeIpnu,
      isAvailable: true,
      gradient: [AppColors.ipnuPrimaryLight, AppColors.ipnuPrimaryDark],
    ),
    DocumentItem(
      title: 'Kartu Identitas',
      description: 'Pembuatan kartu identitas anggota IPNU',
      icon: Icons.credit_card,
      route: RouteNames.kartuIdentitasIpnu,
      isAvailable: true,
      gradient: [AppColors.ipnuPrimaryLight, AppColors.ipnuPrimaryDark],
    ),
    DocumentItem(
      title: 'Sertifikat Kaderisasi',
      description: 'Pembuatan sertifikat kaderisasi untuk anggota IPNU',
      icon: Icons.workspace_premium,
      route: RouteNames.sertifikatKaderisasiIpnu,
      isAvailable: true,
      gradient: [AppColors.ipnuPrimaryLight, AppColors.ipnuPrimaryDark],
    ),
    DocumentItem(
      title: 'Berita Acara Rapat Formatur',
      description: 'Dokumentasi rapat formatur untuk pemilihan ketua',
      icon: Icons.note,
      route: RouteNames.beritaAcaraRapatFormaturIpnu,
      isAvailable: true,
      gradient: [AppColors.ipnuPrimaryLight, AppColors.ipnuPrimaryDark],
    ),
    DocumentItem(
      title: 'Surat Keterangan',
      description: 'Surat keterangan untuk keperluan administrasi',
      icon: Icons.assignment,
      route: RouteNames.suratKeteranganIpnu,
      isAvailable: false,
      gradient: [AppColors.ipnuPrimaryLight, AppColors.ipnuPrimaryDark],
    ),

    DocumentItem(
      title: 'Surat Tugas',
      description: 'Pembuatan surat tugas kegiatan IPNU',
      icon: Icons.work,
      route: RouteNames.suratTugasIpnu,
      isAvailable: false,
      gradient: [AppColors.ipnuPrimaryLight, AppColors.ipnuPrimaryDark],
    ),
    DocumentItem(
      title: 'Proposal Kegiatan',
      description: 'Template proposal untuk kegiatan IPNU',
      icon: Icons.event_note,
      route: RouteNames.proposalIpnu,
      isAvailable: false,
      gradient: [AppColors.ipnuPrimaryLight, AppColors.ipnuPrimaryDark],
    ),
  ];

  static List<DocumentItem> get getDocumentsIppnu => [
    DocumentItem(
      title: 'Surat Permohonan Pengesahan',
      description: 'Pengajuan surat pengesahan untuk kepengurusan IPPNU',
      icon: Icons.description,
      route: RouteNames.suratPermohonanPengesahanIppnu,
      isAvailable: true,
      gradient: [AppColors.ippnuPrimaryLight, AppColors.ippnuPrimaryDark],
    ),
    DocumentItem(
      title: 'Surat Keputusan',
      description: 'Pembuatan surat keputusan untuk kepengurusan IPPNU',
      icon: Icons.gavel,
      route: RouteNames.suratKeputusanIppnu,
      isAvailable: true,
      gradient: [AppColors.ippnuPrimaryLight, AppColors.ippnuPrimaryDark],
    ),
    DocumentItem(
      title: 'Susunan Pengurus',
      description: 'Susunan kepengurusan organisasi IPPNU',
      icon: Icons.groups,
      route: RouteNames.susunanPengurusIppnu,
      isAvailable: true,
      gradient: [AppColors.ippnuPrimaryLight, AppColors.ippnuPrimaryDark],
    ),
    DocumentItem(
      title: 'Curriculum Vitae',
      description: 'Template CV untuk anggota IPPNU',
      icon: Icons.person,
      route: RouteNames.curriculumVitaeIppnu,
      isAvailable: true,
      gradient: [AppColors.ippnuPrimaryLight, AppColors.ippnuPrimaryDark],
    ),
    DocumentItem(
      title: 'Kartu Identitas',
      description: 'Pembuatan kartu identitas anggota IPPNU',
      icon: Icons.credit_card,
      route: RouteNames.kartuIdentitasIppnu,
      isAvailable: true,
      gradient: [AppColors.ippnuPrimaryLight, AppColors.ippnuPrimaryDark],
    ),
    DocumentItem(
      title: 'Sertifikat Kaderisasi',
      description: 'Pembuatan sertifikat kaderisasi untuk anggota IPPNU',
      icon: Icons.workspace_premium,
      route: RouteNames.sertifikatKaderisasiIppnu,
      isAvailable: true,
      gradient: [AppColors.ippnuPrimaryLight, AppColors.ippnuPrimaryDark],
    ),
    DocumentItem(
      title: 'Surat Keterangan',
      description: 'Surat keterangan untuk keperluan administrasi',
      icon: Icons.assignment,
      route: RouteNames.suratKeteranganIppnu,
      isAvailable: false,
      gradient: [AppColors.ipnuPrimaryLight, AppColors.ipnuPrimaryDark],
    ),
    DocumentItem(
      title: 'Surat Tugas',
      description: 'Pembuatan surat tugas kegiatan IPPNU',
      icon: Icons.work,
      route: RouteNames.suratTugasIppnu,
      isAvailable: false,
      gradient: [AppColors.ipnuPrimaryLight, AppColors.ipnuPrimaryDark],
    ),
    DocumentItem(
      title: 'Proposal Kegiatan',
      description: 'Template proposal untuk kegiatan IPPNU',
      icon: Icons.event_note,
      route: RouteNames.proposalIppnu,
      isAvailable: false,
      gradient: [AppColors.ipnuPrimaryLight, AppColors.ipnuPrimaryDark],
    ),
  ];
}
