import 'package:flutter/material.dart';
import 'package:gen_surat/core/themes/app_colors.dart';
import 'package:gen_surat/presentation/pages/document_menu/models/document_item.dart';
import 'package:gen_surat/presentation/routes/route_names.dart';

class DocumentConstants {
  static List<DocumentItem> get getDocumentsIpnu => [
    DocumentItem(
      title: 'Surat Permohonan Pengesahan',
      description: 'Pembuatan surat permohonan pengesahan',
      icon: Icons.description,
      route: RouteNames.suratPermohonanPengesahanIpnu,
      isAvailable: true,
      gradient: [AppColors.ipnuPrimaryLight, AppColors.ipnuPrimaryDark],
    ),
    DocumentItem(
      title: 'Surat Keputusan',
      description: 'Pembuatan surat keputusan Rapat Anggota',
      icon: Icons.gavel,
      route: RouteNames.suratKeputusanIpnu,
      isAvailable: true,
      gradient: [AppColors.ipnuPrimaryLight, AppColors.ipnuPrimaryDark],
    ),
    DocumentItem(
      title: 'Berita Acara Pemilihan Ketua',
      description: 'Pembuatan dokumen Berita acara pemilihan ketua',
      icon: Icons.event,
      route: RouteNames.beritaAcaraPemilihanKetuaIpnu,
      isAvailable: true,
      gradient: [AppColors.ipnuPrimaryLight, AppColors.ipnuPrimaryDark],
    ),
    DocumentItem(
      title: 'Susunan Pengurus',
      description: 'Pembuatan Susunan kepengurusan IPNU',
      icon: Icons.groups,
      route: RouteNames.susunanPengurusIpnu,
      isAvailable: true,
      gradient: [AppColors.ipnuPrimaryLight, AppColors.ipnuPrimaryDark],
    ),
    DocumentItem(
      title: 'Curriculum Vitae',
      description: 'Pembuatan CV untuk Ketua, Sekretaris, dan Bendahara IPNU',
      icon: Icons.person,
      route: RouteNames.curriculumVitaeIpnu,
      isAvailable: true,
      gradient: [AppColors.ipnuPrimaryLight, AppColors.ipnuPrimaryDark],
    ),
    DocumentItem(
      title: 'Kartu Identitas',
      description: 'Pembuatan dokumen upload kartu identitas Ketua, Sekretaris, dan Bendahara IPNU',
      icon: Icons.credit_card,
      route: RouteNames.kartuIdentitasIpnu,
      isAvailable: true,
      gradient: [AppColors.ipnuPrimaryLight, AppColors.ipnuPrimaryDark],
    ),
    DocumentItem(
      title: 'Sertifikat Kaderisasi',
      description: 'Pembuatan dokumen upload sertifikat kaderisasi Ketua, Sekretaris, dan Bendahara IPNU',
      icon: Icons.workspace_premium,
      route: RouteNames.sertifikatKaderisasiIpnu,
      isAvailable: true,
      gradient: [AppColors.ipnuPrimaryLight, AppColors.ipnuPrimaryDark],
    ),
    DocumentItem(
      title: 'Berita Acara Rapat Formatur',
      description: 'Pembuatan dokumen berita acara rapat formatur untuk pembentukan pengurus',
      icon: Icons.note,
      route: RouteNames.beritaAcaraRapatFormaturIpnu,
      isAvailable: true,
      gradient: [AppColors.ipnuPrimaryLight, AppColors.ipnuPrimaryDark],
    ),
    DocumentItem(
      title: 'Surat Keterangan',
      description: 'Surat keterangan untuk keperluan administrasi',
      icon: Icons.assignment,
      route: RouteNames.suratKeteranganIpnu,
      isAvailable: false,
      gradient: [AppColors.ipnuPrimaryLight, AppColors.ipnuPrimaryDark],
    ),

    DocumentItem(
      title: 'Surat Tugas',
      description: 'Pembuatan surat tugas kegiatan IPNU',
      icon: Icons.work,
      route: RouteNames.suratTugasIpnu,
      isAvailable: false,
      gradient: [AppColors.ipnuPrimaryLight, AppColors.ipnuPrimaryDark],
    ),
    DocumentItem(
      title: 'Proposal Kegiatan',
      description: 'Template proposal untuk kegiatan IPNU',
      icon: Icons.event_note,
      route: RouteNames.proposalIpnu,
      isAvailable: false,
      gradient: [AppColors.ipnuPrimaryLight, AppColors.ipnuPrimaryDark],
    ),
  ];

  static List<DocumentItem> get getDocumentsIppnu => [
    DocumentItem(
      title: 'Surat Permohonan Pengesahan',
      description: 'Pembuatan surat permohonan pengesahan',
      icon: Icons.description,
      route: RouteNames.suratPermohonanPengesahanIppnu,
      isAvailable: true,
      gradient: [AppColors.ippnuPrimaryLight, AppColors.ippnuPrimaryDark],
    ),
    DocumentItem(
      title: 'Surat Keputusan',
      description: 'Pembuatan surat keputusan Rapat Anggota',
      icon: Icons.gavel,
      route: RouteNames.suratKeputusanIppnu,
      isAvailable: true,
      gradient: [AppColors.ippnuPrimaryLight, AppColors.ippnuPrimaryDark],
    ),
    DocumentItem(
      title: 'Berita Acara Pemilihan Ketua',
      description: 'Pembuatan dokumen Berita acara pemilihan ketua',
      icon: Icons.event,
      route: RouteNames.beritaAcaraPemilihanKetuaIppnu,
      isAvailable: true,
      gradient: [AppColors.ippnuPrimaryLight, AppColors.ippnuPrimaryDark],
    ),
    DocumentItem(
      title: 'Susunan Pengurus',
      description: 'Pembuatan Susunan kepengurusan IPPNU',
      icon: Icons.groups,
      route: RouteNames.susunanPengurusIppnu,
      isAvailable: true,
      gradient: [AppColors.ippnuPrimaryLight, AppColors.ippnuPrimaryDark],
    ),
    DocumentItem(
      title: 'Curriculum Vitae',
      description: 'Pembuatan CV untuk Ketua, Sekretaris, dan Bendahara IPPNU',
      icon: Icons.person,
      route: RouteNames.curriculumVitaeIppnu,
      isAvailable: true,
      gradient: [AppColors.ippnuPrimaryLight, AppColors.ippnuPrimaryDark],
    ),
    DocumentItem(
      title: 'Kartu Identitas',
      description: 'Pembuatan dokumen upload kartu identitas Ketua, Sekretaris, dan Bendahara IPPNU',
      icon: Icons.credit_card,
      route: RouteNames.kartuIdentitasIppnu,
      isAvailable: true,
      gradient: [AppColors.ippnuPrimaryLight, AppColors.ippnuPrimaryDark],
    ),
    DocumentItem(
      title: 'Sertifikat Kaderisasi',
      description: 'Pembuatan dokumen upload sertifikat kaderisasi Ketua, Sekretaris, dan Bendahara IPPNU',
      icon: Icons.workspace_premium,
      route: RouteNames.sertifikatKaderisasiIppnu,
      isAvailable: true,
      gradient: [AppColors.ippnuPrimaryLight, AppColors.ippnuPrimaryDark],
    ),
    DocumentItem(
      title: 'Berita Acara Formatur Pembentukan Pengurus Harian',
      description:
          'Pembuatan dokumen berita acara rapat formatur untuk pembentukan pengurus harian oleh tim formatur',
      icon: Icons.assignment_turned_in,
      route: RouteNames.beritaAcaraFormaturPembentukanPengurusHarianIppnu,
      isAvailable: true,
      gradient: [AppColors.ippnuPrimaryLight, AppColors.ippnuPrimaryDark],
    ),
    DocumentItem(
      title: 'Berita Acara Penyusunan Pengurus',
      description: 'Pembuatan dokumen berita acara hasil penyusunan kepengurusan lengkap oleh pengurus harian',
      icon: Icons.description_outlined,
      route: RouteNames.beritaAcaraPenyusunanPengurusIppnu,
      isAvailable: true,
      gradient: [AppColors.ippnuPrimaryLight, AppColors.ippnuPrimaryDark],
    ),
    DocumentItem(
      title: 'Surat Keterangan',
      description: 'Surat keterangan untuk keperluan administrasi',
      icon: Icons.assignment,
      route: RouteNames.suratKeteranganIppnu,
      isAvailable: false,
      gradient: [AppColors.ipnuPrimaryLight, AppColors.ipnuPrimaryDark],
    ),
    DocumentItem(
      title: 'Surat Tugas',
      description: 'Pembuatan surat tugas kegiatan IPPNU',
      icon: Icons.work,
      route: RouteNames.suratTugasIppnu,
      isAvailable: false,
      gradient: [AppColors.ipnuPrimaryLight, AppColors.ipnuPrimaryDark],
    ),
    DocumentItem(
      title: 'Proposal Kegiatan',
      description: 'Template proposal untuk kegiatan IPPNU',
      icon: Icons.event_note,
      route: RouteNames.proposalIppnu,
      isAvailable: false,
      gradient: [AppColors.ipnuPrimaryLight, AppColors.ipnuPrimaryDark],
    ),
  ];
}
